# Generated by Django 5.2.3 on 2025-06-29 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('content', models.TextField()),
                ('client_type', models.CharField(max_length=20)),
                ('image_url', models.URLField(max_length=50)),
                ('place_name', models.CharField(max_length=20)),
                ('content_title', models.CharField(max_length=20)),
                ('content_number_character', models.CharField(max_length=20)),
                ('content_talkstyle', models.CharField(max_length=20)),
                ('content_aspect', models.CharField(max_length=20)),
                ('written_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-written_date'],
            },
        ),
    ]
