# Generated by Django 5.2.3 on 2025-06-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='컨텐츠 관점')),
            ],
        ),
        migrations.CreateModel(
            name='ContentNumberCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='글자 수 특성')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTalkstyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='말투 스타일')),
            ],
        ),
        migrations.CreateModel(
            name='ContentTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='컨텐츠 주제')),
            ],
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_aspect',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_number_character',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_talkstyle',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='content_title',
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_url',
            field=models.CharField(max_length=50),
        ),
    ]
