# Generated by Django 5.2.3 on 2025-06-29 15:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_contentaspect_contentnumbercharacter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='고객 이름')),
                ('client_type', models.CharField(choices=[('place', '장소'), ('shopping', '쇼핑'), ('web_document', '웹 문서')], default='place', max_length=20, verbose_name='클라이언트 타입')),
                ('image_url', models.CharField(blank=True, max_length=200, verbose_name='클라이언트 이미지 URL')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSubhead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='컨텐츠 서브헤드')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subheads', to='blog.client', verbose_name='관련 고객')),
            ],
            options={
                'unique_together': {('client', 'name')},
            },
        ),
        migrations.RenameModel(
            old_name='ContentNumberCharacter',
            new_name='NumberCharacter',
        ),
        migrations.RenameModel(
            old_name='ContentTalkstyle',
            new_name='TalkStyle',
        ),
        migrations.DeleteModel(
            name='ContentTitle',
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-written_date'], 'verbose_name': '블로그 게시물', 'verbose_name_plural': '블로그 게시물'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='client_type',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='place_name',
            field=models.CharField(max_length=50, verbose_name='장소명'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='written_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='작성일'),
        ),
        migrations.AddField(
            model_name='blog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blogs', to='blog.client', verbose_name='클라이언트'),
        ),
    ]
