# Generated by Django 5.2.3 on 2025-06-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_client_contentsubhead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='place_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='장소명'),
        ),
    ]
