# Generated by Django 5.2.3 on 2025-06-29 17:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_place_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': '클라이언트', 'verbose_name_plural': '클라이언트'},
        ),
        migrations.AlterModelOptions(
            name='contentaspect',
            options={'verbose_name': '글의 대상', 'verbose_name_plural': '글의 대상'},
        ),
        migrations.AlterModelOptions(
            name='contentsubhead',
            options={'verbose_name': '글 주제', 'verbose_name_plural': '글 주제'},
        ),
        migrations.AlterModelOptions(
            name='numbercharacter',
            options={'verbose_name': '글자수', 'verbose_name_plural': '글자수'},
        ),
        migrations.AlterModelOptions(
            name='talkstyle',
            options={'verbose_name': '글 어투', 'verbose_name_plural': '글 어투'},
        ),
        migrations.AlterUniqueTogether(
            name='contentsubhead',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='blog',
            name='b_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='B_제목'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.client', verbose_name='클라이언트'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='place_name',
            field=models.CharField(default='온라인', max_length=200, verbose_name='장소명'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='written_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='작성일'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('personal', '개인'), ('corporate', '기업'), ('government', '정부/공공기관'), ('startup', '스타트업')], default='personal', max_length=20, verbose_name='클라이언트 유형'),
        ),
        migrations.AlterField(
            model_name='client',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='이미지 URL'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='클라이언트 이름'),
        ),
        migrations.AlterField(
            model_name='contentaspect',
            name='name',
            field=models.CharField(max_length=200, verbose_name='글의 대상'),
        ),
        migrations.AlterField(
            model_name='contentsubhead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subheads', to='blog.client', verbose_name='관련 클라이언트'),
        ),
        migrations.AlterField(
            model_name='contentsubhead',
            name='name',
            field=models.CharField(max_length=200, verbose_name='글 주제'),
        ),
        migrations.AlterField(
            model_name='numbercharacter',
            name='name',
            field=models.CharField(max_length=100, verbose_name='글자수'),
        ),
        migrations.AlterField(
            model_name='talkstyle',
            name='name',
            field=models.CharField(max_length=100, verbose_name='글 어투'),
        ),
    ]
