# Generated by Django 5.2.3 on 2025-06-29 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_client_options_alter_contentaspect_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_write',
            field=models.BooleanField(default=False, verbose_name='글작성 완료'),
        ),
    ]
