# Generated by Django 5.2.3 on 2025-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_blog_write'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
