# Generated by Django 5.2.3 on 2025-07-05 05:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_client_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='키워드')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_keywords', to='blog.client', verbose_name='클라이언트')),
            ],
            options={
                'verbose_name': '쇼핑 키워드',
                'verbose_name_plural': '쇼핑 키워드',
                'unique_together': {('client', 'keyword')},
            },
        ),
        migrations.CreateModel(
            name='KeywordClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_date', models.DateField(default=django.utils.timezone.now, verbose_name='클릭 날짜')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='클릭 횟수')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='blog.shoppingkeyword', verbose_name='쇼핑 키워드')),
            ],
            options={
                'verbose_name': '키워드 클릭 기록',
                'verbose_name_plural': '키워드 클릭 기록',
                'unique_together': {('keyword', 'click_date')},
            },
        ),
    ]
