# Generated by Django 5.2.3 on 2025-07-05 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_shoppingkeyword_keywordclick'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordclick',
            options={'ordering': ['-click_date'], 'verbose_name': '키워드 클릭 기록', 'verbose_name_plural': '키워드 클릭 기록'},
        ),
        migrations.AddField(
            model_name='shoppingkeyword',
            name='is_click_target',
            field=models.BooleanField(default=False, verbose_name='클릭 대상 키워드'),
        ),
        migrations.AddField(
            model_name='shoppingkeyword',
            name='main_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_keywords', to='blog.shoppingkeyword', verbose_name='메인 키워드'),
        ),
    ]
