# Generated by Django 5.2.3 on 2025-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_keywordclick_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingkeyword',
            name='is_click_target',
        ),
        migrations.AddField(
            model_name='shoppingkeyword',
            name='keyword_group',
            field=models.CharField(default='기본', max_length=50, verbose_name='키워드 그룹'),
        ),
    ]
