# Generated by Django 5.2.3 on 2025-07-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_shoppingkeyword_is_click_target_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='완성여부'),
        ),
        migrations.AddField(
            model_name='client',
            name='payment_amount',
            field=models.IntegerField(default=0, verbose_name='결재금액'),
        ),
        migrations.AlterField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('place', '플레이스'), ('shopping', '쇼핑'), ('auto_keyword', '자동완성'), ('web_rank', '네이버 웹문서'), ('google_rank', '구글 순위')], default='personal', max_length=20, verbose_name='클라이언트 유형'),
        ),
    ]
