# Generated by Django 5.2.3 on 2025-07-14 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_client_is_completed_client_payment_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='비용 이름')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='항시(자동 반복)')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='지출일')),
            ],
            options={
                'verbose_name': '비용',
                'verbose_name_plural': '비용',
            },
        ),
    ]
