# Generated by Django 5.2.3 on 2025-07-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingkeyword',
            name='main_keyword',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='메인 키워드'),
        ),
    ]
