# Generated by Django 5.2.3 on 2025-07-14 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_shoppingkeyword_main_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingkeyword',
            name='main_keyword',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_keywords', to='blog.shoppingkeyword', verbose_name='메인 키워드'),
        ),
    ]
