# Generated by Django 5.2.3 on 2025-07-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_shoppingkeyword_main_keyword'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='그룹명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '키워드 그룹',
                'verbose_name_plural': '키워드 그룹',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='shoppingkeyword',
            name='keyword_group',
        ),
        migrations.AddField(
            model_name='shoppingkeyword',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='shopping_keywords', to='blog.keywordgroup', verbose_name='키워드 그룹'),
        ),
    ]
