# Generated by Django 5.2.3 on 2025-08-22 04:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_keywordgroup_remove_shoppingkeyword_keyword_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at'], 'verbose_name': '클라이언트', 'verbose_name_plural': '클라이언트'},
        ),
        migrations.AddField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성일'),
        ),
    ]
