# Generated by Django 5.2.3 on 2026-05-24 17:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_client_options_client_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCopyCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_date', models.DateField(default=django.utils.timezone.now, verbose_name='복사 날짜')),
                ('copy_count', models.PositiveIntegerField(default=0, verbose_name='복사 횟수')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_counts', to='blog.blog', verbose_name='블로그')),
            ],
            options={
                'verbose_name': '블로그 복사 기록',
                'verbose_name_plural': '블로그 복사 기록',
                'ordering': ['-copy_date'],
                'unique_together': {('blog', 'copy_date')},
            },
        ),
    ]
